Implement button with test and styles
isdi-coders-2023/coding-adventure-Maximiliano-Gutierrez-front-202301-BCN pull request #4
Opened 2023-02-28 15:28 UTC by Maximiliano1979

2023-02-28 15:39 UTC, bertoforteza requested changes

2023-02-28 15:39 UTC, bertoforteza commented on src/components/Button/ButtonStyled.tsx
> +  background-color: #cccf18;
Usa variables para los colores, los font-size y font-family. Si quieres puedes probar un `ThemeProvider`

2023-02-28 15:39 UTC, bertoforteza commented on src/components/Button/ButtonStyled.tsx
> +    width: 320;
El width no cambia en desktop, creo que había un fallo en figma. De todas maneras tampoco le estabas pasando unidad a este valor.

2023-02-28 15:39 UTC, bertoforteza commented on src/components/Button/Button.test.tsx
> +      const expectedButton = screen.getByRole("button", { name: insideText });
Aquí no recoges un `expectedButton`, corrige el naming.
Revisa también el workflow de testing porque está fallando.

2023-02-28 15:59 UTC, Maximiliano1979 commented
Estoy viendo ahora que puede pasar con el test

2023-03-01 14:18 UTC, Maximiliano1979 commented on src/components/Button/ButtonStyled.tsx
> +  background-color: #cccf18;
Esto está corregido

2023-03-01 14:18 UTC, Maximiliano1979 commented on src/components/Button/ButtonStyled.tsx
> +    width: 320;
Lo he arreglado

2023-03-01 14:20 UTC, Maximiliano1979 commented on src/components/Button/Button.test.tsx
> +      const expectedButton = screen.getByRole("button", { name: insideText });
El testing lo reviso, no me pasa porque me da este error: Cannot find module 'styled-components' from 'src/components/Button/ButtonStyled.tsx'

2023-03-01 14:45 UTC, catatarelli commented on src/components/Button/Button.test.tsx
> +    test("Then it should render button with the text 'Sign Up'", () => {
"Then it should show"

2023-03-01 14:48 UTC, catatarelli requested changes

2023-03-01 14:48 UTC, catatarelli commented on src/components/Button/ButtonStyled.tsx
> +    opacity: 57%;
la opacity va cuando el button esta disabled

2023-03-01 14:58 UTC, Maximiliano1979 commented on src/components/Button/ButtonStyled.tsx
> +    opacity: 57%;
Realizado

2023-03-01 15:00 UTC, merged